CREATE TABLE AssetStatus (
    AssetStatID CHAR PRIMARY KEY,
    ADescription VARCHAR2(25) UNIQUE NOT NULL
);


CREATE TABLE Genre (
    GenreID INTEGER PRIMARY KEY,
    GDescription VARCHAR2(25) UNIQUE NOT NULL
);


CREATE TABLE Asset (
    AssetID INTEGER PRIMARY KEY,
    AssetStatID CHAR REFERENCES AssetStatus(AssetStatID) ON DELETE CASCADE,
    Title VARCHAR2(50) NOT NULL,
    Author VARCHAR2(25) NOT NULL,
    GenreID INTEGER REFERENCES Genre(GenreID) ON DELETE CASCADE,
    Publisher VARCHAR2(50),
    CoverImage BLOB,
    Copies INTEGER
);


CREATE TABLE AssetHistory (
    AssetHistoryID INTEGER PRIMARY KEY,
    AssetID INTEGER REFERENCES Asset(AssetID) ON DELETE CASCADE,
    TimeBorrowed DATE NOT NULL,
    TimeReturn DATE NOT NULL
);

CREATE TABLE AssetRole (
    ARoleID INTEGER PRIMARY KEY,
    ARoleDescription VARCHAR2(25) UNIQUE NOT NULL
);


CREATE TABLE PhysicalAsset (
    AssetID INTEGER PRIMARY KEY REFERENCES Asset(AssetID) ON DELETE CASCADE,
    ARoleID INTEGER REFERENCES AssetRole (ARoleID) ON DELETE CASCADE
);


CREATE TABLE PhysBook (
    AssetID INTEGER PRIMARY KEY REFERENCES Asset(AssetID) ON DELETE CASCADE,
    ISBN VARCHAR2(25)
);


CREATE TABLE PhysDVD (
    AssetID INTEGER PRIMARY KEY REFERENCES Asset(AssetID) ON DELETE CASCADE
);


CREATE TABLE PhysCD (
    AssetID INTEGER PRIMARY KEY REFERENCES Asset(AssetID) ON DELETE CASCADE,
    CDDB1 VARCHAR2(25)
);

CREATE TABLE DigitalAsset (
    AssetID INTEGER PRIMARY KEY REFERENCES Asset(AssetID) ON DELETE CASCADE,
    ARoleID INTEGER REFERENCES AssetRole(ARoleID) ON DELETE CASCADE
);


CREATE TABLE DigiBook (
    AssetID INTEGER PRIMARY KEY REFERENCES Asset(AssetID) ON DELETE CASCADE,
    DigiISBN VARCHAR2(25)
);


CREATE TABLE DigiDVD (
    AssetID INTEGER PRIMARY KEY REFERENCES Asset(AssetID) ON DELETE CASCADE
);


CREATE TABLE DigiCD (
    AssetID INTEGER PRIMARY KEY REFERENCES Asset(AssetID) ON DELETE CASCADE,
    DigiCDDB1 VARCHAR2(25)
);
