-- drop views first
DROP VIEW vUserFacilityBookings;
DROP VIEW vAssetsBorrowed;
DROP VIEW vUserActivities;

-- drop tables
DROP TABLE FACILITYCOMPUTER;
DROP TABLE RESOURCECOMPUTER;
DROP TABLE FACILITYSTUDYROOM;
DROP TABLE FACILITYBOOKINGINFO;
DROP TABLE FACILITYBOOKING;
DROP TABLE FACILITY;
DROP TABLE JOBPOSTING;

DROP TABLE ACTIVITYEVENT;
DROP TABLE ACTIVITYPROGRAM;
DROP TABLE PROGRAM;
DROP TABLE EVENT;
DROP TABLE LIBBRANCH;
DROP TABLE STREETLOOKUP;
DROP TABLE HOST;

DROP TABLE USERHISTORY;
DROP TABLE USERLIBRARIAN;
DROP TABLE USERLIBRARYMEMBER;
DROP TABLE USERSTATUS;
DROP TABLE "User" CASCADE CONSTRAINTS PURGE;
DROP TABLE ROLE;
DROP TABLE ADDRESS;

DROP TABLE PHYSBOOK;
DROP TABLE PHYSDVD;
DROP TABLE PHYSCD;
DROP TABLE PHYSICALASSET;

DROP TABLE DIGIBOOK;
DROP TABLE DIGIDVD;
DROP TABLE DIGICD;

DROP TABLE DIGITALASSET;
DROP TABLE ASSETHISTORY;
DROP TABLE ASSETROLE;
DROP TABLE ASSET;
DROP TABLE ASSETSTATUS;
DROP TABLE GENRE;

DROP TABLE Phone;
DROP TABLE Email;
DROP TABLE PostalCode;
