CREATE TABLE Role (
    RoleID INTEGER PRIMARY KEY CHECK (RoleID BETWEEN 1 AND 3),
    RoleName VARCHAR2(25) UNIQUE NOT NULL
);

CREATE TABLE Email (
    EmailID INTEGER PRIMARY KEY,
    EmailAddress VARCHAR2(100) UNIQUE NOT NULL
);

CREATE TABLE Address(
    Postal VARCHAR2(7)  PRIMARY KEY NOT NULL,
    Street VARCHAR2(50) NOT NULL
);

CREATE TABLE "User"(
    UserID INTEGER PRIMARY KEY,
    FirstName VARCHAR2(25) NOT NULL,
    LastName VARCHAR2(25) NOT NULL,
    PhoneNum VARCHAR2(25) NOT NULL,
    StreetNum INTEGER NOT NULL,
    Postal VARCHAR2(7) REFERENCES Address(Postal) ON DELETE CASCADE,
    EmailID INTEGER REFERENCES Email(EmailID),
    RoleID INTEGER REFERENCES Role(RoleID) ON DELETE CASCADE
);


CREATE TABLE UserStatus (
    UStatusID INTEGER PRIMARY KEY CHECK (UStatusID BETWEEN 1 AND 3),
    StatusDescript VARCHAR2(25) UNIQUE NOT NULL
);



CREATE TABLE UserLibraryMember (
    UserID INTEGER PRIMARY KEY REFERENCES "User"(UserID) ON DELETE CASCADE,
    CardNumber VARCHAR2(25) UNIQUE NOT NULL,
    UStatusID INTEGER REFERENCES UserStatus(UStatusID) ON DELETE CASCADE
);



CREATE TABLE UserLibrarian (
    UserID INTEGER PRIMARY KEY REFERENCES "User"(UserID) ON DELETE CASCADE
);


CREATE TABLE UserHistory (
    UserHistoryID INTEGER PRIMARY KEY,
    UserID INTEGER REFERENCES "User"(UserID) ON DELETE CASCADE,
    AssetID INTEGER REFERENCES Asset(AssetID) ON DELETE CASCADE
);
